name = "pickleball"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNzA5OGI2NmYtYjU4Yi00ZGQwLThjMjMtNTg4NTQ0OTVjOWNmIiwidGVuYW50X2lkIjoiZGNlODg1N2QyNWNiMjNmZjIzZGI0OGUxN2ZjNTExYTdhMjNjZTk2MjJlYmY0OTM1N2I5MzY0Mzk1MTc3MTBiNyIsImludGVybmFsX3NlY3JldCI6IjViNDFiM2U2LWI4MzItNGRkMy1iMjI4LWFmZjM1YzkxMmNjNCJ9.ONFkvtrBP2Q4E9O7S4p4RJ_sNT0RMiSbI2CkY5EOz18"
JWT_SECRET="haard@1808"